#line 1 "C:\\Users\\mwolfram\\Documents\\Arduino Projects\\yoradio\\yoRadio\\myoptions.h"
#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,43,46&i=15,16,17&v=2,4,33 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */
/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define PLAYER_FORCE_MONO	true
#define I2S_DOUT			2
#define I2S_BCLK			4
#define I2S_LRC			    33

#include <ETH.h>

// --- TTGO T-Internet-POE (LAN8720A) wiring ---
static const int ETH_PHY_ADDR   = 0;
static const int ETH_POWER_PIN  = -1;    // no dedicated power pin on this board
static const int ETH_MDC_PIN    = 23;
static const int ETH_MDIO_PIN   = 18;
static const eth_phy_type_t ETH_TYPE = ETH_PHY_LAN8720;
// Most T-Internet-POE boards use 50 MHz clock on GPIO17 (ESP32 outputs it)
static const eth_clock_mode_t ETH_CLK_MODE = ETH_CLOCK_GPIO17_OUT;
// If link never comes up, try ETH_CLOCK_GPIO0_OUT (rare older revs).


#endif